-- ZUARA APP — esquema base para migración Neon -> Supabase.
-- No contiene datos productivos ni credenciales.
-- Ejecutar después de crear el proyecto Supabase de ZUARA.
-- La autenticación usa Supabase Auth; la tabla usuarios conserva la estructura
-- de negocio actual y añade auth_user_id para vincular cada cuenta.

create schema if not exists private;

create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  documento text,
  nombre text not null default '',
  telefono text,
  correo text,
  pais text,
  estado text,
  municipio text,
  direccion_entrega text,
  punto_referencia text,
  coordenadas text,
  tipo_envio text,
  fecha_registro text,
  registrado_por text
);

create table if not exists public.proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  correo text,
  telefono text,
  direccion text,
  tipo text,
  fecha_registro text,
  registrado_por text
);

create table if not exists public.almacenes (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  ubicacion text,
  fecha_registro text,
  registrado_por text
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  descripcion text,
  fecha_registro text,
  registrado_por text
);

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  categoria_id bigint,
  proveedor_id bigint,
  descripcion text not null default '',
  unidad_medida text,
  stock_minimo integer default 0,
  precio_usd real default 0,
  estado text default 'ACTIVO',
  codigo_barras text,
  foto text,
  fecha_registro text,
  registrado_por text
);

create table if not exists public.movimientos (
  id bigint generated by default as identity primary key,
  consecutivo text,
  fecha_registro text,
  tipo text,
  producto_id bigint,
  cantidad real default 0,
  costo_unitario real default 0,
  almacen_origen_id bigint,
  almacen_destino_id bigint,
  motivo text,
  documento text,
  registrado_por text
);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  consecutivo text,
  fecha_registro text,
  fecha_facturacion text,
  cliente_nombre text,
  cliente_telefono text,
  direccion_entrega text,
  total_eur real default 0,
  total_bs real default 0,
  tasa_bcv_euro_aplicada real default 0,
  tasa_binance_aplicada real default 0,
  porcentaje_brecha_aplicado real default 0,
  estado text,
  registrado_por text,
  metodo_pago text
);

create table if not exists public.detalle_nota_entrega (
  id bigint generated by default as identity primary key,
  consecutivo text,
  producto_id bigint references public.productos(id) on delete restrict,
  cantidad real default 0,
  descuento real default 0,
  precio_unitario_euro_snapshot real default 0,
  subtotal_euro_snapshot real default 0,
  total_euro_snapshot real default 0,
  precio_unitario_bs_snapshot real default 0,
  subtotal_bs_snapshot real default 0,
  total_bs_snapshot real default 0
);

create table if not exists public.notas_credito (
  id bigint generated by default as identity primary key,
  consecutivo text,
  fecha_registro text,
  consecutivo_origen text,
  cliente_nombre text,
  total_eur real default 0,
  total_bs real default 0,
  motivo text,
  registrado_por text,
  saldo_usado_eur real default 0,
  saldo_usado_bs real default 0,
  estado text default 'DISPONIBLE'
);

create table if not exists public.detalle_nota_credito (
  id bigint generated by default as identity primary key,
  consecutivo_nc text,
  producto_id bigint references public.productos(id) on delete restrict,
  cantidad real default 0,
  precio_eur real default 0,
  precio_bs real default 0,
  subtotal_eur real default 0,
  subtotal_bs real default 0
);

create table if not exists public.historico_precios_dia (
  fecha text primary key,
  json_data text
);

create table if not exists public.historico_tasas (
  id bigint generated by default as identity primary key,
  fecha text not null,
  hora text,
  dolar_bcv real default 0,
  binance real default 0,
  bybit real default 0,
  dolar_promedio real default 0,
  euro_bcv real default 0,
  zelle real default 0,
  paypal real default 0,
  brecha real default 0,
  registrado_por text
);

create table if not exists public.historico_coberturas (
  id bigint generated by default as identity primary key,
  fecha_registro text,
  rango_evaluado text,
  fecha_pico_maximo text,
  porcentaje_cobertura real default 0,
  factor_proteccion real default 1,
  registrado_por text,
  estado text
);

create table if not exists public.configuracion (
  clave text primary key,
  valor text
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null default '',
  usuario text not null unique,
  contrasena text,
  activo boolean default true,
  es_admin boolean default false,
  permisos text default '[]',
  protegido boolean default false,
  fecha_registro text,
  auth_user_id uuid unique references auth.users(id) on delete set null
);

-- Índices usados por la lógica de inventario, facturación, tasas y seguridad.
create index if not exists idx_usuarios_auth_user_id on public.usuarios(auth_user_id);
create index if not exists idx_movimientos_producto_id on public.movimientos(producto_id);
create index if not exists idx_movimientos_fecha on public.movimientos(fecha_registro);
create index if not exists idx_movimientos_documento on public.movimientos(documento);
create index if not exists idx_ventas_fecha on public.ventas(fecha_registro);
create index if not exists idx_ventas_fecha_facturacion on public.ventas(fecha_facturacion);
create index if not exists idx_detalle_venta_consecutivo on public.detalle_nota_entrega(consecutivo);
create index if not exists idx_detalle_nc_consecutivo on public.detalle_nota_credito(consecutivo_nc);
create index if not exists idx_nc_cliente on public.notas_credito(cliente_nombre);
create index if not exists idx_tasas_fecha_hora on public.historico_tasas(fecha desc, hora desc);
create index if not exists idx_coberturas_estado_id on public.historico_coberturas(estado, id desc);
create index if not exists idx_productos_categoria on public.productos(categoria_id);
create index if not exists idx_productos_proveedor on public.productos(proveedor_id);

insert into public.configuracion(clave, valor)
values ('permitir_descuentos','true')
on conflict (clave) do nothing;

-- Los almacenes 9998/9999 forman parte de la lógica actual y deben conservarse.
insert into public.almacenes(id, nombre, ubicacion, fecha_registro, registrado_por)
values
  (9999, 'Devoluciones por Venta (BLOQUEADO)', 'Sistema Automático', now()::text, 'Sistema'),
  (9998, 'Almacén de Merma (BLOQUEADO)', 'Sistema Automático', now()::text, 'Sistema')
on conflict (id) do nothing;

-- Cobertura inicial compatible con el sistema actual.
insert into public.historico_coberturas(
  fecha_registro, rango_evaluado, fecha_pico_maximo,
  porcentaje_cobertura, factor_proteccion, registrado_por, estado
)
select now()::text, 'Inicial', 'N/A', 0.20, 1.20, 'Sistema', 'ACTIVO'
where not exists (select 1 from public.historico_coberturas);

-- ---------------------------------------------------------------------------
-- Helpers de autorización. Se mantienen fuera del esquema público.
-- ---------------------------------------------------------------------------

create or replace function private.app_user_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select u.id
  from public.usuarios u
  where u.auth_user_id = (select auth.uid())
    and u.activo = true
  limit 1
$$;

create or replace function private.app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1
    from public.usuarios u
    where u.auth_user_id = (select auth.uid())
      and u.activo = true
      and u.es_admin = true
  )
$$;

create or replace function private.app_has_permission(p_permiso text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_permisos jsonb;
begin
  if (select private.app_is_admin()) then
    return true;
  end if;

  select
    case
      when trim(coalesce(u.permisos,'')) like '[%'
        then trim(u.permisos)::jsonb
      else '[]'::jsonb
    end
  into v_permisos
  from public.usuarios u
  where u.auth_user_id = (select auth.uid())
    and u.activo = true
  limit 1;

  return coalesce((v_permisos ->> p_permiso)::boolean, false)
      or (p_permiso = 'agregar_tasa' and coalesce((v_permisos ->> 'parametros')::boolean, false));
exception when others then
  return false;
end;
$$;

revoke all on function private.app_user_id() from public;
revoke all on function private.app_is_admin() from public;
revoke all on function private.app_has_permission(text) from public;
grant usage on schema private to authenticated;
grant execute on function private.app_user_id() to authenticated;
grant execute on function private.app_is_admin() to authenticated;
grant execute on function private.app_has_permission(text) to authenticated;

-- ---------------------------------------------------------------------------
-- RLS: ningún visitante anónimo recibe acceso a los datos.
-- Las operaciones sensibles que requieren transacción pasan por funciones/RPC
-- o Edge Functions; las tablas siguen protegidas como segunda barrera.
-- ---------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'clientes','proveedores','almacenes','categorias','productos','movimientos',
    'ventas','detalle_nota_entrega','notas_credito','detalle_nota_credito',
    'historico_precios_dia','historico_tasas','historico_coberturas',
    'configuracion','usuarios'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on table public.%I from anon', t);
  end loop;
end $$;

-- Grants mínimos para la API autenticada.
grant select, insert, update, delete on public.clientes, public.proveedores,
  public.almacenes, public.categorias, public.productos, public.movimientos,
  public.ventas, public.detalle_nota_entrega, public.notas_credito,
  public.detalle_nota_credito, public.historico_precios_dia, public.historico_tasas,
  public.historico_coberturas, public.configuracion, public.usuarios
to authenticated;

-- Las secuencias de tablas con identity también deben ser utilizables por
-- operaciones de inserción directas/RPC que no usen el service role.
grant usage, select on all sequences in schema public to authenticated;

-- Política genérica por módulo para las tablas CRUD simples.
create policy clientes_select on public.clientes for select to authenticated
  using ((select private.app_has_permission('clientes')));
create policy clientes_insert on public.clientes for insert to authenticated
  with check ((select private.app_has_permission('clientes')));
create policy clientes_update on public.clientes for update to authenticated
  using ((select private.app_has_permission('clientes')))
  with check ((select private.app_has_permission('clientes')));
create policy clientes_delete on public.clientes for delete to authenticated
  using ((select private.app_has_permission('clientes')));

create policy proveedores_select on public.proveedores for select to authenticated
  using ((select private.app_has_permission('proveedores')));
create policy proveedores_insert on public.proveedores for insert to authenticated
  with check ((select private.app_has_permission('proveedores')));
create policy proveedores_update on public.proveedores for update to authenticated
  using ((select private.app_has_permission('proveedores')))
  with check ((select private.app_has_permission('proveedores')));
create policy proveedores_delete on public.proveedores for delete to authenticated
  using ((select private.app_has_permission('proveedores')));

create policy almacenes_select on public.almacenes for select to authenticated
  using ((select private.app_has_permission('almacenes')));
create policy almacenes_insert on public.almacenes for insert to authenticated
  with check ((select private.app_has_permission('almacenes')));
create policy almacenes_update on public.almacenes for update to authenticated
  using ((select private.app_has_permission('almacenes')))
  with check ((select private.app_has_permission('almacenes')));
create policy almacenes_delete on public.almacenes for delete to authenticated
  using ((select private.app_has_permission('almacenes')) and id not in (9998,9999));

create policy categorias_select on public.categorias for select to authenticated
  using ((select private.app_has_permission('categorias')));
create policy categorias_insert on public.categorias for insert to authenticated
  with check ((select private.app_has_permission('categorias')));
create policy categorias_update on public.categorias for update to authenticated
  using ((select private.app_has_permission('categorias')))
  with check ((select private.app_has_permission('categorias')));
create policy categorias_delete on public.categorias for delete to authenticated
  using ((select private.app_has_permission('categorias')));

create policy productos_select on public.productos for select to authenticated
  using ((select private.app_has_permission('productos')));
create policy productos_insert on public.productos for insert to authenticated
  with check ((select private.app_has_permission('productos')));
create policy productos_update on public.productos for update to authenticated
  using ((select private.app_has_permission('productos')))
  with check ((select private.app_has_permission('productos')));
create policy productos_delete on public.productos for delete to authenticated
  using ((select private.app_has_permission('productos')));

create policy movimientos_select on public.movimientos for select to authenticated
  using ((select private.app_has_permission('kardex') or private.app_has_permission('movimientos')));
create policy movimientos_insert on public.movimientos for insert to authenticated
  with check ((select private.app_has_permission('movimientos')));
create policy movimientos_update on public.movimientos for update to authenticated
  using ((select private.app_is_admin()));
create policy movimientos_delete on public.movimientos for delete to authenticated
  using ((select private.app_is_admin()));

-- Historiales y facturación: lectura para usuarios autenticados con módulo.
create policy ventas_select on public.ventas for select to authenticated
  using ((select private.app_has_permission('historial_ventas') or private.app_has_permission('ventas')));
create policy ventas_insert on public.ventas for insert to authenticated
  with check ((select private.app_has_permission('ventas')));
create policy ventas_update on public.ventas for update to authenticated
  using ((select private.app_has_permission('ventas') or private.app_has_permission('historial_ventas')));
create policy ventas_delete on public.ventas for delete to authenticated
  using ((select private.app_is_admin()));

create policy detalle_venta_select on public.detalle_nota_entrega for select to authenticated
  using ((select private.app_has_permission('historial_ventas') or private.app_has_permission('ventas')));
create policy detalle_venta_write on public.detalle_nota_entrega for insert to authenticated
  with check ((select private.app_has_permission('ventas')));
create policy detalle_venta_delete on public.detalle_nota_entrega for delete to authenticated
  using ((select private.app_is_admin()));

create policy nc_select on public.notas_credito for select to authenticated
  using ((select private.app_has_permission('historial_ventas') or private.app_has_permission('ventas')));
create policy nc_insert on public.notas_credito for insert to authenticated
  with check ((select private.app_has_permission('historial_ventas')));
create policy nc_update on public.notas_credito for update to authenticated
  using ((select private.app_has_permission('ventas') or private.app_has_permission('historial_ventas')));
create policy nc_delete on public.notas_credito for delete to authenticated
  using ((select private.app_is_admin()));

create policy detalle_nc_select on public.detalle_nota_credito for select to authenticated
  using ((select private.app_has_permission('historial_ventas') or private.app_has_permission('ventas')));
create policy detalle_nc_insert on public.detalle_nota_credito for insert to authenticated
  with check ((select private.app_has_permission('historial_ventas')));
create policy detalle_nc_delete on public.detalle_nota_credito for delete to authenticated
  using ((select private.app_is_admin()));

-- Precios históricos: consulta desde lista de precios/reportes.
create policy historico_precios_select on public.historico_precios_dia for select to authenticated
  using ((select private.app_has_permission('lista_precios') or private.app_has_permission('reportes') or private.app_has_permission('ventas')));
create policy historico_precios_write on public.historico_precios_dia for insert to authenticated
  with check ((select private.app_has_permission('lista_precios') or private.app_has_permission('ventas')));
create policy historico_precios_update on public.historico_precios_dia for update to authenticated
  using ((select private.app_has_permission('lista_precios') or private.app_has_permission('ventas')));

-- Tasas: agregar_tasa permite insertar; parámetros controla consulta/edición/borrado.
create policy tasas_select on public.historico_tasas for select to authenticated
  using ((select private.app_has_permission('parametros')));
create policy tasas_insert on public.historico_tasas for insert to authenticated
  with check ((select private.app_has_permission('agregar_tasa')));
create policy tasas_update on public.historico_tasas for update to authenticated
  using ((select private.app_has_permission('parametros')))
  with check ((select private.app_has_permission('parametros')));
create policy tasas_delete on public.historico_tasas for delete to authenticated
  using ((select private.app_has_permission('parametros')));

create policy coberturas_select on public.historico_coberturas for select to authenticated
  using ((select private.app_has_permission('parametros')));
create policy coberturas_insert on public.historico_coberturas for insert to authenticated
  with check ((select private.app_has_permission('parametros')));
create policy coberturas_update on public.historico_coberturas for update to authenticated
  using ((select private.app_has_permission('parametros')))
  with check ((select private.app_has_permission('parametros')));
create policy coberturas_delete on public.historico_coberturas for delete to authenticated
  using ((select private.app_has_permission('parametros')));

create policy configuracion_select on public.configuracion for select to authenticated
  using (true);
create policy configuracion_update on public.configuracion for update to authenticated
  using ((select private.app_has_permission('configuracion')))
  with check ((select private.app_has_permission('configuracion')));

create policy usuarios_select on public.usuarios for select to authenticated
  using ((select private.app_has_permission('usuarios')));
create policy usuarios_insert on public.usuarios for insert to authenticated
  with check ((select private.app_has_permission('usuarios')));
create policy usuarios_update on public.usuarios for update to authenticated
  using ((select private.app_has_permission('usuarios')))
  with check ((select private.app_has_permission('usuarios')));
create policy usuarios_delete on public.usuarios for delete to authenticated
  using ((select private.app_has_permission('usuarios')));

-- El precio objetivo solo puede ser modificado por administrador, igual que en
-- la versión Flask. El resto de campos del producto conserva su permiso normal.
create or replace function private.enforce_producto_price_admin()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
     and coalesce(new.precio_usd,0) is distinct from coalesce(old.precio_usd,0)
     and not (select private.app_is_admin()) then
    raise exception 'No es posible realizar esta operación.';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_productos_precio_admin on public.productos;
create trigger trg_productos_precio_admin
before update on public.productos
for each row execute function private.enforce_producto_price_admin();

revoke all on function private.enforce_producto_price_admin() from public, anon, authenticated;

-- Validación de fechas de tasas a nivel DB: nunca acepta 2026-02-31 ni formatos
-- distintos de YYYY-MM-DD, incluso si alguien intenta escribir fuera de la UI.
create or replace function private.validar_fecha_iso_real(p_fecha text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare d date;
begin
  if p_fecha is null or p_fecha !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2} then
    return false;
  end if;
  begin
    d := p_fecha::date;
  exception when others then
    return false;
  end;
  return d::text = p_fecha;
end;
$$;

alter table public.historico_tasas
  drop constraint if exists historico_tasas_fecha_valida;
alter table public.historico_tasas
  add constraint historico_tasas_fecha_valida
  check (private.validar_fecha_iso_real(fecha));

-- Elimina permisos anónimos y deja las funciones privadas fuera de la API.
revoke all on schema private from public;
grant usage on schema private to authenticated;
 then
    return false;
  end if;
  begin
    d := p_fecha::date;
  exception when others then
    return false;
  end;
  return d::text = p_fecha;
end;
$$;

alter table public.historico_tasas
  drop constraint if exists historico_tasas_fecha_valida;
alter table public.historico_tasas
  add constraint historico_tasas_fecha_valida
  check (private.validar_fecha_iso_real(fecha));

-- Elimina permisos anónimos y deja las funciones privadas fuera de la API.
revoke all on schema private from public;
grant usage on schema private to authenticated;
